### ISSUE TITLE
Can you enable this for multiple manefests?

### ISSUE THREAD

**Issue by MrHinsh** [dhilmathy/update-manifest-extension#3]
I want to use this to update the version property of all of my .net Core .csproj files... it would be much easier if it did all of them at once.

**Comment by dhilmathy** [comment]
@MrHinsh Thanks for bring this up. Released version [2.0.5](https://marketplace.visualstudio.com/items?itemName=dhilmathy.update-manifest) including this change; you can now specify multiple file paths separated using a `|` delimiter. 

Fixed in PR #4
